@serilog_demo_HostAddress = https://localhost:7271

GET {{serilog_demo_HostAddress}}/weatherforecast
Accept: application/json

###

GET {{serilog_demo_HostAddress}}/weatherforecast?summary=Chilly
Accept: application/json

###

POST  {{serilog_demo_HostAddress}}/throw-error
Accept: application/json

###

POST  {{serilog_demo_HostAddress}}/test-loggers
Accept: application/json

###